# Generated by Django 3.2.4 on 2021-06-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_question_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='picture',
        ),
    ]
